sudo:  required
dist: trusty
language: node_js
node_js:
- 6.9.5
script:
- sleep 3
- bluemix login --apikey $BLUEMIX_API_KEY
deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    manifest: manifest.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASSWORD
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    api: $BLUEMIX_TARGET
    on:
      branch: master
